[package]
name = "vm"
version = "0.1.0"
authors = ["stackswithans <stexor12@gmail.com>"]
edition = "2018"

[dependencies]
unicode-segmentation = "1.9.0"

[lib]
name = "amanda"
crate-type = ["cdylib"]
