name: linux-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: |
        python3.8 -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run build
      run: |
        env/bin/python3.8 setup.py
        dist/amanda ./examples/hello_world.ama
